<?php

namespace Valpuia\MizoramKhua\Database\Seeders\Villages;

use Illuminate\Database\Seeder;
use Valpuia\MizoramKhua\Models\MizoramVillage;

class LungleiDistrictSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        //  sources: https://lgdirectory.gov.in/

        $districtVillages = [
            ['id' => '446', 'mizoram_district_id' => '7', 'name' => 'Balungsuri'],
            ['id' => '447', 'mizoram_district_id' => '7', 'name' => 'Belkhai'],
            ['id' => '448', 'mizoram_district_id' => '7', 'name' => 'Belpei'],
            ['id' => '449', 'mizoram_district_id' => '7', 'name' => 'Belthei'],
            ['id' => '450', 'mizoram_district_id' => '7', 'name' => 'Bindiasora'],
            ['id' => '451', 'mizoram_district_id' => '7', 'name' => 'Bolia'],
            ['id' => '452', 'mizoram_district_id' => '7', 'name' => 'Bualte'],
            ['id' => '453', 'mizoram_district_id' => '7', 'name' => 'Buarpui'],
            ['id' => '454', 'mizoram_district_id' => '7', 'name' => 'Buknuam'],
            ['id' => '455', 'mizoram_district_id' => '7', 'name' => 'Bunghmun'],
            ['id' => '456', 'mizoram_district_id' => '7', 'name' => 'Bungtlang West'],
            ['id' => '457', 'mizoram_district_id' => '7', 'name' => 'Changpui'],
            ['id' => '458', 'mizoram_district_id' => '7', 'name' => 'Chawilung South'],
            ['id' => '459', 'mizoram_district_id' => '7', 'name' => 'Chawngte L'],
            ['id' => '460', 'mizoram_district_id' => '7', 'name' => 'Chengkawllui'],
            ['id' => '461', 'mizoram_district_id' => '7', 'name' => 'Chengpui'],
            ['id' => '462', 'mizoram_district_id' => '7', 'name' => 'Chhuahthum'],
            ['id' => '463', 'mizoram_district_id' => '7', 'name' => 'Chhumkhum'],
            ['id' => '464', 'mizoram_district_id' => '7', 'name' => 'Chithar'],
            ['id' => '465', 'mizoram_district_id' => '7', 'name' => 'College Veng'],
            ['id' => '466', 'mizoram_district_id' => '7', 'name' => 'Dawn'],
            ['id' => '467', 'mizoram_district_id' => '7', 'name' => 'Dengsur'],
            ['id' => '468', 'mizoram_district_id' => '7', 'name' => 'Devasuri'],
            ['id' => '469', 'mizoram_district_id' => '7', 'name' => 'Diblibagh'],
            ['id' => '470', 'mizoram_district_id' => '7', 'name' => 'Electric Veng'],
            ['id' => '471', 'mizoram_district_id' => '7', 'name' => 'Farm Veng'],
            ['id' => '472', 'mizoram_district_id' => '7', 'name' => 'Haulawng'],
            ['id' => '473', 'mizoram_district_id' => '7', 'name' => 'Hauruang'],
            ['id' => '474', 'mizoram_district_id' => '7', 'name' => 'Hlumte'],
            ['id' => '475', 'mizoram_district_id' => '7', 'name' => 'Hmundo'],
            ['id' => '476', 'mizoram_district_id' => '7', 'name' => 'Hmuntlang'],
            ['id' => '477', 'mizoram_district_id' => '7', 'name' => 'Hrangchalkawn'],
            ['id' => '478', 'mizoram_district_id' => '7', 'name' => 'Kalapani'],
            ['id' => '479', 'mizoram_district_id' => '7', 'name' => 'Kauchhuah'],
            ['id' => '480', 'mizoram_district_id' => '7', 'name' => 'Kawlhawk'],
            ['id' => '481', 'mizoram_district_id' => '7', 'name' => 'Khawmawi'],
            ['id' => '482', 'mizoram_district_id' => '7', 'name' => 'Khojoysury'],
            ['id' => '483', 'mizoram_district_id' => '7', 'name' => 'Laisawral'],
            ['id' => '484', 'mizoram_district_id' => '7', 'name' => 'Lalnutui'],
            ['id' => '485', 'mizoram_district_id' => '7', 'name' => 'Lokisuri'],
            ['id' => '486', 'mizoram_district_id' => '7', 'name' => 'Luangmual'],
            ['id' => '487', 'mizoram_district_id' => '7', 'name' => 'Lungchem'],
            ['id' => '488', 'mizoram_district_id' => '7', 'name' => 'Lunglawn'],
            ['id' => '489', 'mizoram_district_id' => '7', 'name' => 'Lunglei Bazar Veng'],
            ['id' => '490', 'mizoram_district_id' => '7', 'name' => 'Lunglei Chanmari'],
            ['id' => '491', 'mizoram_district_id' => '7', 'name' => 'Lungpuizawl'],
            ['id' => '492', 'mizoram_district_id' => '7', 'name' => 'Lungrang South'],
            ['id' => '493', 'mizoram_district_id' => '7', 'name' => 'Lungsen - I'],
            ['id' => '494', 'mizoram_district_id' => '7', 'name' => 'Lungsen II'],
            ['id' => '495', 'mizoram_district_id' => '7', 'name' => 'Madhiasora'],
            ['id' => '496', 'mizoram_district_id' => '7', 'name' => 'Malsury'],
            ['id' => '497', 'mizoram_district_id' => '7', 'name' => 'Mamte'],
            ['id' => '498', 'mizoram_district_id' => '7', 'name' => 'Marpara South'],
            ['id' => '499', 'mizoram_district_id' => '7', 'name' => 'Mausen'],
            ['id' => '500', 'mizoram_district_id' => '7', 'name' => 'Mautlang'],
            ['id' => '501', 'mizoram_district_id' => '7', 'name' => 'Mauzam'],
            ['id' => '502', 'mizoram_district_id' => '7', 'name' => 'Mualcheng South'],
            ['id' => '503', 'mizoram_district_id' => '7', 'name' => 'Mualthuam North'],
            ['id' => '504', 'mizoram_district_id' => '7', 'name' => 'Mualthuam’S’'],
            ['id' => '505', 'mizoram_district_id' => '7', 'name' => 'Muriskata'],
            ['id' => '506', 'mizoram_district_id' => '7', 'name' => 'New.Balukiasuri'],
            ['id' => '507', 'mizoram_district_id' => '7', 'name' => 'New Sachan'],
            ['id' => '508', 'mizoram_district_id' => '7', 'name' => 'Nunsury - I'],
            ['id' => '509', 'mizoram_district_id' => '7', 'name' => 'Nunsury II'],
            ['id' => '510', 'mizoram_district_id' => '7', 'name' => 'Old Ralvawng'],
            ['id' => '511', 'mizoram_district_id' => '7', 'name' => 'Phairuangkai'],
            ['id' => '512', 'mizoram_district_id' => '7', 'name' => 'Puankhai'],
            ['id' => '513', 'mizoram_district_id' => '7', 'name' => 'Pukpui'],
            ['id' => '514', 'mizoram_district_id' => '7', 'name' => 'Putlungasih'],
            ['id' => '515', 'mizoram_district_id' => '7', 'name' => 'Rahsi Veng'],
            ['id' => '516', 'mizoram_district_id' => '7', 'name' => 'Ralvawng'],
            ['id' => '517', 'mizoram_district_id' => '7', 'name' => 'Ramlaitui'],
            ['id' => '518', 'mizoram_district_id' => '7', 'name' => 'Ramthar Veng'],
            ['id' => '519', 'mizoram_district_id' => '7', 'name' => 'Rangte'],
            ['id' => '520', 'mizoram_district_id' => '7', 'name' => 'Rolui'],
            ['id' => '521', 'mizoram_district_id' => '7', 'name' => 'Rotlang West'],
            ['id' => '522', 'mizoram_district_id' => '7', 'name' => 'Rualalung'],
            ['id' => '523', 'mizoram_district_id' => '7', 'name' => 'Runtung'],
            ['id' => '524', 'mizoram_district_id' => '7', 'name' => 'Sachan'],
            ['id' => '525', 'mizoram_district_id' => '7', 'name' => 'Sailen'],
            ['id' => '526', 'mizoram_district_id' => '7', 'name' => 'Sairep'],
            ['id' => '527', 'mizoram_district_id' => '7', 'name' => 'Salem'],
            ['id' => '528', 'mizoram_district_id' => '7', 'name' => 'Sazaikawn'],
            ['id' => '529', 'mizoram_district_id' => '7', 'name' => 'Sekhum'],
            ['id' => '530', 'mizoram_district_id' => '7', 'name' => 'Serhuan'],
            ['id' => '531', 'mizoram_district_id' => '7', 'name' => 'Serkawn'],
            ['id' => '532', 'mizoram_district_id' => '7', 'name' => 'Serte'],
            ['id' => '533', 'mizoram_district_id' => '7', 'name' => 'Sertlangpui'],
            ['id' => '534', 'mizoram_district_id' => '7', 'name' => 'Sesawm'],
            ['id' => '535', 'mizoram_district_id' => '7', 'name' => 'Sethlun'],
            ['id' => '536', 'mizoram_district_id' => '7', 'name' => 'Silkur'],
            ['id' => '537', 'mizoram_district_id' => '7', 'name' => 'S.Khawlek'],
            ['id' => '538', 'mizoram_district_id' => '7', 'name' => 'S.Lungdai'],
            ['id' => '539', 'mizoram_district_id' => '7', 'name' => 'Sugarbasora'],
            ['id' => '540', 'mizoram_district_id' => '7', 'name' => 'Sumasumi'],
            ['id' => '541', 'mizoram_district_id' => '7', 'name' => 'Tablabagh'],
            ['id' => '542', 'mizoram_district_id' => '7', 'name' => 'Tawipui \'N\' I'],
            ['id' => '543', 'mizoram_district_id' => '7', 'name' => 'Tawipui \'N\' II'],
            ['id' => '544', 'mizoram_district_id' => '7', 'name' => 'Tawipui South'],
            ['id' => '545', 'mizoram_district_id' => '7', 'name' => 'Thaizawl'],
            ['id' => '546', 'mizoram_district_id' => '7', 'name' => 'Thangpui'],
            ['id' => '547', 'mizoram_district_id' => '7', 'name' => 'Thangte'],
            ['id' => '548', 'mizoram_district_id' => '7', 'name' => 'Thehlep'],
            ['id' => '549', 'mizoram_district_id' => '7', 'name' => 'Theiriat'],
            ['id' => '550', 'mizoram_district_id' => '7', 'name' => 'Thenhlum'],
            ['id' => '551', 'mizoram_district_id' => '7', 'name' => 'Thingfal'],
            ['id' => '552', 'mizoram_district_id' => '7', 'name' => 'Thlengang'],
            ['id' => '553', 'mizoram_district_id' => '7', 'name' => 'Thualthu'],
            ['id' => '554', 'mizoram_district_id' => '7', 'name' => 'Thuampui'],
            ['id' => '555', 'mizoram_district_id' => '7', 'name' => 'Tiperaghat'],
            ['id' => '556', 'mizoram_district_id' => '7', 'name' => 'Tlabung'],
            ['id' => '557', 'mizoram_district_id' => '7', 'name' => 'Tleu'],
            ['id' => '558', 'mizoram_district_id' => '7', 'name' => 'Tuichawng'],
            ['id' => '559', 'mizoram_district_id' => '7', 'name' => 'Tuisen Chhuah'],
            ['id' => '560', 'mizoram_district_id' => '7', 'name' => 'Ukdasuri (Tuilet)'],
            ['id' => '561', 'mizoram_district_id' => '7', 'name' => 'Undermanik'],
            ['id' => '562', 'mizoram_district_id' => '7', 'name' => 'Upper Lungrang South'],
            ['id' => '563', 'mizoram_district_id' => '7', 'name' => 'Vairawkai'],
            ['id' => '564', 'mizoram_district_id' => '7', 'name' => 'Vaisam'],
            ['id' => '565', 'mizoram_district_id' => '7', 'name' => 'Vanhne'],
            ['id' => '566', 'mizoram_district_id' => '7', 'name' => 'Venghlun'],
            ['id' => '567', 'mizoram_district_id' => '7', 'name' => 'Venglai'],
            ['id' => '568', 'mizoram_district_id' => '7', 'name' => 'Zawlpui'],
            ['id' => '569', 'mizoram_district_id' => '7', 'name' => 'Zehtet'],
            ['id' => '570', 'mizoram_district_id' => '7', 'name' => 'Zobawk North'],
            ['id' => '571', 'mizoram_district_id' => '7', 'name' => 'Zobawk South'],
            ['id' => '572', 'mizoram_district_id' => '7', 'name' => 'Zodin'],
            ['id' => '573', 'mizoram_district_id' => '7', 'name' => 'Zohnuai'],
            ['id' => '574', 'mizoram_district_id' => '7', 'name' => 'Zotlang'],
            ['id' => '575', 'mizoram_district_id' => '7', 'name' => 'Zotuitlang'],
        ];

        MizoramVillage::upsert($districtVillages, ['id']);
    }
}
